pollutants:
  - code: "44201"
    name: "Ozone"
    unit: "ppm"
  - code: "42401"
    name: "Sulfur Dioxide"
    unit: "ppb"
  - code: "42101"
    name: "Carbon Monoxide"
    unit: "ppm"
  - code: "42602"
    name: "Nitrogen Dioxide"
    unit: "ppb"
  - code: "81102"
    name: "PM10 Total 0-10um STP"
    unit: "ug/m3"
  - code: "88101"
    name: "PM2.5 - Local Conditions"
    unit: "ug/m3"
